### ISSUE TITLE
Error on Hifi-gan synthesis attempt

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#29]
Getting the following error code in the GUI upon attempting to use the newly added Hifi-gan option for voice synthesis:
>Type: RuntimeError
Text: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 276, in synthesis_post File "synthesis\synthesize.py", line 118, in synthesize File "synthesis\hifigan.py", line 77, in generate_audio_hifigan File "torch\nn\modules\module.py", line 727, in _call_impl File "synthesis\hifigan_model.py", line 110, in forward File "torch\nn\modules\module.py", line 727, in _call_impl File "torch\nn\modules\conv.py", line 258, in forward RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by BenAAndrew** [comment]
@RayDAnt3D What model did you upload and are you using an NVIDIA GPU?

**Comment by BenAAndrew** [comment]
@RayDAnt3D Closing as fixed in 0.7.1

**Comment by RayDAnt3D** [comment]
Fyi still getting a variation of the same error under release 0.7.1:
>Type: RuntimeError
Text: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 280, in synthesis_post File "synthesis\synthesize.py", line 118, in synthesize File "synthesis\hifigan.py", line 78, in generate_audio_hifigan File "torch\nn\modules\module.py", line 727, in _call_impl File "synthesis\hifigan_model.py", line 167, in forward File "torch\nn\modules\module.py", line 727, in _call_impl File "torch\nn\modules\conv.py", line 258, in forward RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by RayDAnt3D** [comment]
@BenAAndrew refreshing the exe download fixed it. Thanks!
